return {
	PlaceObj('ModItemOptionNumber', {
		'name', "cdr_tactical_min",
		'DisplayName', "Tactical Min Height",
		'DefaultValue', 100,
		'MinValue', 10,
		'MaxValue', 2000,
		'StepSize', 50,
	}),
	PlaceObj('ModItemOptionNumber', {
		'name', "cdr_tactical_max",
		'DisplayName', "Tactical Max Height",
		'DefaultValue', 1100,
		'MinValue', 100,
		'MaxValue', 3000,
		'StepSize', 50,
	}),
	PlaceObj('ModItemOptionNumber', {
		'name', "cdr_overview_min",
		'DisplayName', "Overview Min Height",
		'DefaultValue', 100,
		'MinValue', 10,
		'MaxValue', 2000,
		'StepSize', 50,
	}),
	PlaceObj('ModItemOptionNumber', {
		'name', "cdr_overview_max",
		'DisplayName', "Overview Max Height",
		'DefaultValue', 1100,
		'MinValue', 100,
		'MaxValue', 5000,
		'StepSize', 50,
	}),
	PlaceObj('ModItemOptionNumber', {
		'name', "cdr_zoom_step",
		'DisplayName', "Zoom Step",
		'DefaultValue', 15,
		'MinValue', 5,
		'MaxValue', 50,
		'StepSize', 5,
	}),
	PlaceObj('ModItemOptionNumber', {
		'name', "cdr_pitch_angle",
		'DisplayName', "Pitch Angle",
		'DefaultValue', 60,
		'MinValue', 45,
		'MaxValue', 75,
		'StepSize', 5,
	}),
	PlaceObj('ModItemOptionBool', {
		'name', "cdr_toggle_AdjustCombatCamera",
		'DisplayName', "Override AdjustCombatCamera",
		'Help', "Prevents the game from overriding our camera settings during the enemy turn.",
		'DefaultValue', true,
	}),
	PlaceObj('ModItemOptionBool', {
		'name', "cdr_toggle_CinematicCamera",
		'DisplayName', "Disable Cinematic Combat Camera",
		'Help', "Disables cinematic camera shots during attacks.",
		'DefaultValue', true,
	}),
	PlaceObj('ModItemOptionBool', {
		'name', "cdr_toggle_LockCameraMovement",
		'DisplayName', "Prevent Camera Movement Locking",
		'Help', "Allows moving the camera during combat even when the game normally locks it.",
		'DefaultValue', true,
	}),
	PlaceObj('ModItemOptionBool', {
		'name', "cdr_toggle_SetForceMaxZoom",
		'DisplayName', "Prevent Forced Max Zoom",
		'Help', "Prevents the game from forcing a specific zoom level during certain actions.",
		'DefaultValue', true,
	}),
	PlaceObj('ModItemOptionBool', {
		'name', "cdr_toggle_SetOverview",
		'DisplayName', "Restore Zoom and Pos on Overview Toggle",
		'Help', "Caches and restores camera position and zoom when switching between Tactical and Overview modes.",
		'DefaultValue', true,
	}),
	PlaceObj('ModItemOptionBool', {
		'name', "cdr_toggle_SnapCameraEnemyTurn",
		'DisplayName', "Intercept Enemy Turn Snapping",
		'Help', "Intercepts SnapCameraToObj calls during the enemy turn to prevent unwanted camera jumps.",
		'DefaultValue', true,
	}),
	PlaceObj('ModItemCode', {
		'CodeFileName', "Code/Script.lua",
	}),
	PlaceObj('ModItemLocTable', {
		'language', "English",
		'filename', "Languages/en.csv",
	}),
}