return PlaceObj('ModDef', {
	'title', "Camera Done Right",
	'last_changes', "Beta version",
	'id', "Yb7PXyK",
	'author', "KeldorKatarn",
	'version', 7,
	'lua_revision', 233360,
	'saved_with_revision', 366685,
	'code', {
		"Code/Script.lua",
	},
	'loctables', {
		{
			filename = "Languages/en.csv",
			language = "English",
		},
	},
	'default_options', {
		cdr_overview_max = 1100,
		cdr_overview_min = 100,
		cdr_pitch_angle = 60,
		cdr_tactical_max = 1100,
		cdr_tactical_min = 100,
		cdr_toggle_AdjustCombatCamera = true,
		cdr_toggle_CinematicCamera = true,
		cdr_toggle_CombatCamera = true,
		cdr_toggle_LockCameraMovement = true,
		cdr_toggle_SetForceMaxZoom = true,
		cdr_toggle_SetOverview = true,
		cdr_toggle_SnapCameraEnemyTurn = true,
		cdr_toggle_SnapCameraPlayerActions = true,
		cdr_zoom_step = 15,
	},
	'saved', 1775650782,
	'code_hash', -3608270687547524951,
	'affected_resources', {},
	'steam_id', "3702504040",
	'TagGameSettings', true,
	'TagOther', true,
	'TagUI', true,
})