return PlaceObj('ModDef', {
	'title', "Camera Done Right",
	'description', "[h1]Camera Done Right[/h1]\n\nTake full control of your tactical and overview cameras! Camera Done Right unlocks zoom limits, prevents annoying camera snapping, and gives you a smoother combat experience with highly customizable settings.\n\n[h2]Key Features:[/h2]\n- [b]Unlocked Zoom:[/b] Set your own min/max zoom heights for both Tactical and Overview modes.\n- [b]No More Camera Snapping:[/b] Disable automatic camera jumps during enemy turns or player actions (aiming, moving, attacking).\n- [b]Combat Smoothness:[/b] Disable cinematic kill-cams and tactical zooms that interrupt your view of the battlefield.\n- [b]Free Movement:[/b] Move and rotate your camera freely even when the game tries to lock it during combat.\n- [b]Mode Memory:[/b] Automatically remembers and restores your camera position and zoom level when switching between Tactical and Overview modes.\n- [b]Fully Customizable:[/b] Tweak pitch angles, zoom steps, and more via the Mod Options menu.",
	'image', "Mod/Yb7PXyK/Images/thumbnail.jpg",
	'last_changes', "Fix some cinematic camera issue, aiming perspective and add setting to reduce DOF.",
	'id', "Yb7PXyK",
	'author', "KeldorKatarn",
	'version_major', 1,
	'version_minor', 2,
	'version', 14,
	'lua_revision', 233360,
	'saved_with_revision', 366685,
	'code', {
		"Code/Script.lua",
	},
	'loctables', {
		{
			filename = "Languages/en.csv",
			language = "English",
		},
	},
	'default_options', {
		cdr_CinematicCameraMode = "Default",
		cdr_dof_strength = "100",
		cdr_overview_max = "1100",
		cdr_overview_min = "100",
		cdr_pitch_angle = "60",
		cdr_tactical_max = "1100",
		cdr_tactical_min = "100",
		cdr_toggle_AdjustCombatCamera = true,
		cdr_toggle_CombatCamera = true,
		cdr_toggle_LockCameraMovement = true,
		cdr_toggle_SetForceMaxZoom = true,
		cdr_toggle_SetOverview = true,
		cdr_toggle_SnapCameraEnemyTurn = true,
		cdr_toggle_SnapCameraPlayerActions = true,
		cdr_zoom_step = "15",
	},
	'saved', 1775835763,
	'code_hash', -2920034219384207745,
	'screenshot1', "Mod/Yb7PXyK/Images/screenshot1.jpg",
	'screenshot2', "Mod/Yb7PXyK/Images/screenshot2.jpg",
	'screenshot3', "Mod/Yb7PXyK/Images/screenshot3.jpg",
	'affected_resources', {},
	'steam_id', "3702504040",
	'TagGameSettings', true,
	'TagOther', true,
	'TagUI', true,
})